services:
  sencho:
    image: saelix/sencho:latest
    container_name: sencho
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
      # DATA DIRECTORY
      # Left Side: Where Sencho saves your admin login (Change this if you want it elsewhere)
      # Right Side: Internal container path (DO NOT CHANGE)
      - ./data:/app/data
      
      # STACKS DIRECTORY
      # Left Side: The absolute path to your Docker compose stacks on your server
      # Right Side: Internal container path (DO NOT CHANGE)
      - SENCHO_STACKS_DIR:/app/compose
